### ISSUE TITLE
Sample seems to be broken

### ISSUE THREAD

**Issue by rdmueller** [gitpod-samples/template-jupyter-notebook#2]
when I use this sample, VS Code doesn't find any python interpreter and thus can't start jupyter.
A few days ago, this still worked.

Has the base image been changed? VS Code Version?

There could also be a small chance that my user settings break the setup, but since I know other who experience the same problem...

**Comment by rdmueller** [comment]
Don't know what has been changed, but it works again.

**Comment by axonasif** [comment]
Cool
